apiVersion: skaffold/v1
kind: Config
metadata:
  name: apps
deploy:
  kubectl:
    manifests:
    - k8s/apps.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/apps
  local: {}
