apiVersion: skaffold/v3
kind: Config
metadata:
  name: apps
build:
  artifacts:
    - image: harbor.cyverse.org/de/apps
  tagPolicy:
    gitCommit: {}
  local: {}
  platforms:
    - linux/amd64
manifests:
  rawYaml:
    - k8s/apps.yml
deploy:
  kubectl: {}
