(ns apps.protocols)

(defprotocol Apps
  "A protocol used to provide an abstraction layer for dealing with app metadata."
  (getUser [_])
  (getClientName [_])
  (getJobTypes [_])
  (listSystemIds [_])
  (supportsSystemId [_ system-id])
  (listAppCategories [_ params])
  (listAppsInCategory [_ system-id category-id params])
  (listAppsUnderHierarchy [_ root-iri attr params])
  (adminListAppsUnderHierarchy [_ ontology-version root-iri attr params])
  (listAppsInCommunity [_ community-id params])
  (adminListAppsInCommunity [_ community-id params])
  (searchApps [_ search-term params])
  (listSingleApp [_ system-id app-id])
  (adminSearchApps [_ search-term params])
  (canEditApps [_])
  (addApp [_ system-id app])
  (addAppVersion [_ system-id app admin?])
  (previewCommandLine [_ system-id app])
  (validateDeletionRequest [_ deletion-request])
  (deleteApps [_ deletion-request])
  (getAppJobView [_ system-id app-id] [_ system-id app-id include-hidden-params?])
  (getAppVersionJobView [_ system-id app-id version-id])
  (getAppSubmissionInfo [_ system-id app-id])
  (deleteApp [_ system-id app-id])
  (deleteAppVersion [_ system-id app-id app-version-id])
  (relabelApp [_ system-id app])
  (updateApp [_ system-id app])
  (copyApp [_ system-id app-id])
  (copyAppVersion [_ system-id app-id version-id])
  (getAppDetails [_ system-id app-id admin?])
  (getAppVersionDetails [_ system-id app-id app-version-id admin?])
  (removeAppFavorite [_ system-id app-id])
  (addAppFavorite [_ system-id app-id])
  (isAppPublishable [_ system-id app-id admin?])
  (listToolsInUntrustedRegistries [_ system-id app-id])
  (usesToolsInUntrustedRegistries [_ system-id app-id])
  (createPublicationRequest [_ system-id app untrusted-tools])
  (makeAppPublic [_ system-id app])
  (deleteAppRating [_ system-id app-id])
  (rateApp [_ system-id app-id rating])
  (getAppTaskListing [_ system-id app-id])
  (getAppToolListing [_ system-id app-id])
  (getAppUi [_ system-id app-id])
  (getAppVersionUi [_ system-id app-id version-id])
  (getAppInputIds [_ system-id app-id])
  (addPipeline [_ pipeline])
  (formatPipelineTasks [_ pipeline])
  (updatePipeline [_ pipeline])
  (copyPipeline [_ app-id])
  (editPipeline [_ app-id])
  (listJobs [_ params])
  (listJobStats [_ params])
  (adminListJobsWithExternalIds [_ external-ids])
  (loadAppTables [_ qualified-app-ids])
  (submitJob [_ submission])
  (submitJobStep [_ job-id submission])
  (translateJobStatus [_ job-type status])
  (updateJobStatus [_ job-step job status end-date])
  (getDefaultOutputName [_ io-map source-step])
  (getJobStepStatus [_ job-step])
  (getJobStepHistory [_ job-step])
  (buildNextStepSubmission [_ job-step job])
  (prepareStepSubmission [_ job-id submission])
  (getParamDefinitions [_ system-id app-id])
  (stopJobStep [_ job-step])
  (categorizeApps [_ body])
  (listAppPublicationRequests [_ params])
  (permanentlyDeleteApps [_ body])
  (adminDeleteApp [_ system-id app-id])
  (adminUpdateApp [_ system-id body])
  (adminBlessApp [_ system-id app-id])
  (adminRemoveAppBlessing [_ system-id app-id])
  (getAdminAppCategories [_ params])
  (searchAdminAppCategories [_ params])
  (adminAddCategory [_ system-id body])
  (adminDeleteCategory [_ system-id category-id])
  (adminUpdateCategory [_ system-id body])
  (getAppDocs [_ system-id app-id])
  (getAppIntegrationData [_ system-id app-id])
  (getAppVersionIntegrationData [_ system-id app-id version-id])
  (getToolIntegrationData [_ system-id tool-id])
  (updateAppIntegrationData [_ system-id app-id integration-data-id])
  (updateAppVersionIntegrationData [_ system-id app-id version-id integration-data-id])
  (updateToolIntegrationData [_ system-id tool-id integration-data-id])
  (ownerEditAppDocs [_ system-id app-id body])
  (ownerAddAppDocs [_ system-id app-id body])
  (adminEditAppDocs [_ system-id app-id body])
  (adminAddAppDocs [_ system-id app-id body])
  (listAppPermissions [_ qualified-app-ids params])
  (shareApps [_ sharing-requests])
  (shareAppsWithSubject [_ app-names sharee user-app-sharing-requests])
  (shareAppWithSubject [_ app-names sharee system-id app-id level])
  (unshareApps [_ unsharing-requests])
  (unshareAppsWithSubject [_ app-names sharee app-unsharing-requests])
  (unshareAppWithSubject [_ app-names sharee system-id app-id])
  (hasAppPermission [_ username system-id app-id required-level])
  (supportsJobSharing [_ _]))
